name: pvparena
author: slipcor
main: net.slipcor.pvparena.PVPArena
version: v0.4.3.1
website: http://dev.bukkit.org/server-mods/pvp-arena
commands:
    pvparena:
        description: Base commands for the PVP arena.
        aliases: ['pa']
        usage: |
            /pvparena help
permissions:
    fight.*:
        description: Gives access to all commands
        children:
            fight.admin: true
            fight.user: true
    pvparena.*:
        description: Gives access to all commands
        children:
            pvparena.admin: true
            pvparena.telepass: true
            pvparena.user: true
    fight.admin:
        description: Allows you to administrate the arena
        default: op
    fight.user:
        description: Allows you to use the arena
        default: true
    pvparena.admin:
        description: Allows you to administrate the arena
        default: op
    pvparena.telepass:
        description: Allows you to teleport while in an arena
        default: op
    pvparena.user:
        description: Allows you to use the arena
        default: true